steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/staffvirtual-discord-bot:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/staffvirtual-discord-bot:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'staffvirtual-discord-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/staffvirtual-discord-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '1'
      - '--set-env-vars'
      - 'BRAND_NAME=STAFFVIRTUAL,BRAND_PRIMARY_COLOR=#1888FF,BRAND_SECONDARY_COLOR=#F8F8EB,BRAND_ACCENT_COLOR=#004B8D'

images:
  - 'gcr.io/$PROJECT_ID/staffvirtual-discord-bot:$COMMIT_SHA'
